# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/dicai.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/dicai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/dicai.proto\x12\x05\x64icai\"\x84\x01\n\x0eProcessRequest\x12\x11\n\tinput_ids\x18\x01 \x03(\x05\x12\x15\n\rhidden_states\x18\x02 \x01(\x0c\x12\x1b\n\x13hidden_states_shape\x18\x03 \x03(\x05\x12\x17\n\x0ftarget_provider\x18\x04 \x01(\t\x12\x12\n\nrequest_id\x18\x05 \x01(\t\"\xcd\x01\n\x0fProcessResponse\x12\x15\n\rhidden_states\x18\x01 \x01(\x0c\x12\x1b\n\x13hidden_states_shape\x18\x02 \x03(\x05\x12\x0e\n\x06logits\x18\x03 \x01(\x0c\x12\x14\n\x0clogits_shape\x18\x04 \x03(\x05\x12\x13\n\x0bprovider_id\x18\x05 \x01(\t\x12\x18\n\x10layers_processed\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\r\n\x05\x65rror\x18\x08 \x01(\t\x12\x12\n\nrequest_id\x18\t \x01(\t\"#\n\rHealthRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"\x9d\x01\n\x0eHealthResponse\x12\x13\n\x0bprovider_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06layers\x18\x03 \x01(\t\x12\x13\n\x0blayer_count\x18\x04 \x01(\x05\x12\x16\n\x0ememory_used_mb\x18\x05 \x01(\x03\x12\x17\n\x0fmemory_total_mb\x18\x06 \x01(\x03\x12\x10\n\x08gpu_info\x18\x07 \x01(\t2\xc6\x01\n\x0fProviderService\x12\x38\n\x07Process\x12\x15.dicai.ProcessRequest\x1a\x16.dicai.ProcessResponse\x12\x35\n\x06Health\x12\x14.dicai.HealthRequest\x1a\x15.dicai.HealthResponse\x12\x42\n\rProcessStream\x12\x15.dicai.ProcessRequest\x1a\x16.dicai.ProcessResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.dicai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSREQUEST']._serialized_start=29
  _globals['_PROCESSREQUEST']._serialized_end=161
  _globals['_PROCESSRESPONSE']._serialized_start=164
  _globals['_PROCESSRESPONSE']._serialized_end=369
  _globals['_HEALTHREQUEST']._serialized_start=371
  _globals['_HEALTHREQUEST']._serialized_end=406
  _globals['_HEALTHRESPONSE']._serialized_start=409
  _globals['_HEALTHRESPONSE']._serialized_end=566
  _globals['_PROVIDERSERVICE']._serialized_start=569
  _globals['_PROVIDERSERVICE']._serialized_end=767
# @@protoc_insertion_point(module_scope)
