# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shared/dicai.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'shared/dicai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shared/dicai.proto\x12\x05\x64icai\"\x90\x01\n\rTensorRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x13\n\x0btensor_data\x18\x03 \x01(\x0c\x12\r\n\x05shape\x18\x04 \x03(\x05\x12\r\n\x05\x64type\x18\x05 \x01(\t\x12\x13\n\x0blayer_start\x18\x06 \x01(\x05\x12\x11\n\tlayer_end\x18\x07 \x01(\x05\"w\n\x0eTensorResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0btensor_data\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"\x0f\n\rHealthRequest\"^\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x13\n\x0bmemory_used\x18\x03 \x01(\x02\x12\x14\n\x0cmemory_total\x18\x04 \x01(\x02\x32\x87\x01\n\rTensorService\x12:\n\x0b\x46orwardPass\x12\x14.dicai.TensorRequest\x1a\x15.dicai.TensorResponse\x12:\n\x0bHealthCheck\x12\x14.dicai.HealthRequest\x1a\x15.dicai.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.dicai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORREQUEST']._serialized_start=30
  _globals['_TENSORREQUEST']._serialized_end=174
  _globals['_TENSORRESPONSE']._serialized_start=176
  _globals['_TENSORRESPONSE']._serialized_end=295
  _globals['_HEALTHREQUEST']._serialized_start=297
  _globals['_HEALTHREQUEST']._serialized_end=312
  _globals['_HEALTHRESPONSE']._serialized_start=314
  _globals['_HEALTHRESPONSE']._serialized_end=408
  _globals['_TENSORSERVICE']._serialized_start=411
  _globals['_TENSORSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
